account_app/urls.py
from django.urls import path
from .views import profile_edit_view, signup_view, CustomLoginView, profile_view
from django.contrib.auth.views import LogoutView
app_name = 'account_app'
urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/accounts/login/'), name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', profile_edit_view, name='profile_edit'),
]

idz_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booking/', include('booking_app.urls', namespace='booking_app')),          # маршруты бронирования
    path('accounts/', include('account_app.urls', namespace='account_app')),       # маршруты авторизации
    path('', RedirectView.as_view(url='/booking/rooms/')),  # главная страница
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Hotel Booking{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <div class="nav-left">
            🏨 <a href="/" class="brand">HotelBooking</a>
        </div>
        <div class="nav-right">
            {% if user.is_authenticated %}
                Привет, <a href="{% url 'account_app:profile' %}">{{ user.username }}</a> |
                <form method="post" action="{% url 'account_app:logout' %}" class="logout-form">
                    {% csrf_token %}
                    <button type="submit">Выйти</button>
                </form>
            {% else %}
                <a href="{% url 'account_app:login' %}">Вход</a> |
                <a href="{% url 'account_app:signup' %}">Регистрация</a>
            {% endif %}
        </div>
    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        © 2025 HotelBooking — Бронирование номеров онлайн
    </footer>
</body>
</html>